/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c6c5d4",
        surface: "#f8f9ff",
        outline: "#767683",
        "on-primary-fixed": "#000c62",
        "secondary-fixed": "#d5e3fc",
        "on-secondary-container": "#57657a",
        "on-secondary-fixed": "#0d1c2e",
        "secondary-container": "#d5e3fc",
        "on-background": "#0b1c30",
        error: "#ba1a1a",
        "on-primary-container": "#9aa5ff",
        "primary-fixed-dim": "#bcc2ff",
        "inverse-surface": "#213145",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        secondary: "#515f74",
        "tertiary-container": "#384055",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-tint": "#4955b3",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#dfe0ff",
        "on-primary-fixed-variant": "#303c9a",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary": "#ffffff",
        primary: "#0b1a7d",
        "surface-variant": "#d3e4fe",
        "on-tertiary-fixed": "#131b2e",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#a4acc5",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b9c7df",
        "inverse-primary": "#bcc2ff",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-surface-variant": "#454652",
        "inverse-on-surface": "#eaf1ff",
        tertiary: "#222a3e",
        background: "#f8f9ff",
        "primary-container": "#283593",
        "tertiary-fixed-dim": "#bec6e0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "ui-sans-serif", "system-ui"],
        body: ["Inter", "ui-sans-serif", "system-ui"],
        label: ["Inter", "ui-sans-serif", "system-ui"],
      },
      boxShadow: {
        soft: "0 24px 48px -12px rgba(11, 28, 48, 0.08)",
      },
    },
  },
  plugins: [],
};
